header
MagdalenaSiniawska/cinemania_gr2 pull request #11
Opened 2024-10-18 00:21 UTC by achoma

header zrobiony.  Proszę o sprawdzenie kodu na menu mobilne, bo kod wydaje mi się ok, jak wklepuję go do codepen to działa, a w local host nie otwiera okna modalnego

2024-10-18 17:15 UTC, OstTomasz requested changes
pod tym menu container coś jest namieszane z visibility. Visibility powinno być zależne tylko od klasy is-open

2024-10-18 17:15 UTC, OstTomasz commented on src/html/header.html
> +<header>
usuń <header>

2024-10-18 17:15 UTC, OstTomasz commented on src/html/header.html
> +    <script type="module" src="./js/header.js"></script>
usuń -> jest w main.js

2024-10-18 17:15 UTC, OstTomasz commented on src/index.html
> +    <header id="header"></header>
w środku dodaj      w klamrach "load src="./html/header.html" /"

2024-10-18 17:15 UTC, OstTomasz commented on src/index.html
> +    <header id="header"></header>
przez to nie mogło odczytać Ci buttona i zwracało null

2024-10-19 13:23 UTC, MagdalenaSiniawska reviewed
Komentarze wysłane na Slacku ;)

2024-10-19 20:14 UTC, closed without merging